- name: Setup web server on Amazon Linux 2
  hosts: production
  become: true
  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest

    - name: Enable Amazon Linux Extras for Docker
      shell: amazon-linux-extras enable docker

    - name: Install required packages
      yum:
        name:
          - git
          - python3
          - docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to Docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Clone application repository
      git:
        repo: "https://github.com/your-repo.git"
        dest: /home/ec2-user/app

    - name: Build and run Docker container
      shell: |
        cd /home/ec2-user/app/docker
        docker-compose up -d
      args:
        executable: /bin/bash
