---
- name: Setup Docker environment on EC2 instance
  hosts: production
  become: true
  gather_facts: yes

  tasks:
    - name: Install required packages (git, python3-pip, dnf-utils)
      ansible.builtin.dnf:
        name:
          - git
          - python3-pip
          - dnf-utils
        state: present

    - name: Install Docker on Amazon Linux 2023
      ansible.builtin.dnf:
        name: docker
        state: present

    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Add Docker Compose binary (optional if needed)
      ansible.builtin.shell: |
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose

    - name: Create the .ssh directory if it doesn't exist
      ansible.builtin.file:
        path: /home/centos/.ssh
        state: directory
        mode: '0700'
        owner: ec2-user
        group: ec2-user

    - name: Copy SSH private key to the EC2 instance
      ansible.builtin.copy:
        src: "/home/ec2-user/Final-Workshop---CICD/tohar-keypair.pem"  # Ensure the correct path to your key
        dest: /home/centos/.ssh/id_rsa
        mode: '0600'
        owner: ec2-user
        group: ec2-user

    - name: Clone the app repository from GitHub
      ansible.builtin.git:
        repo: 'https://github.com/toharbarazi/Final-Workshop---CICD.git'
        dest: /home/centos/app
        version: main

    - name: Build Docker image
      ansible.builtin.shell:
        chdir: "/home/centos/app/docker"
        cmd: docker build -t my-app .

    - name: Run Docker container
      ansible.builtin.shell:
        chdir: /home/centos/app/docker
        cmd: docker run -d -p 80:80 my-app

